# -*- coding: utf-8 -*-
"""KNN Test.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1oQTWOWOKS6ACB4671wqVlyQW4DEGBvxe
"""

from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.neighbors import KNeighborsClassifier
from sklearn.metrics import confusion_matrix, accuracy_score

import numpy as np
import pandas as pd

dataset = pd.read_csv('/content/balance-scale.csv')
x = dataset.iloc[:, [1,4]].values
y = dataset.iloc[:, [0]].values

x_train, x_test, y_train, y_test = train_test_split(x, y, test_size = 0.3, random_state = 100)

sc = StandardScaler()
x_train = sc.fit_transform(x_train)
x_test = sc.transform(x_test)

classifier = KNeighborsClassifier(n_neighbors = 5)
classifier.fit(x_train, y_train)

y_pred = classifier.predict(x_test)
print(y_pred)

print('Confusion matrix: \n', confusion_matrix(y_test, y_pred))
print('Accuracy score \n', accuracy_score(y_test, y_pred))