# -*- coding: utf-8 -*-
"""DT.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1hX9eMQ9Ffu2euE75GkdpvcU2kYgNoN7d
"""

import numpy as np

dataset = [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 100]

outliers = []


def outlier_detection(data):
    threshold = 3
    mean = np.mean(data)
    std = np.std(data)
    for i in data:
        Z_score = (i - mean) / std
        if (np.abs(Z_score) > threshold):
            outliers.append(i)
    return outliers


point = outlier_detection(dataset)
print('The Outliers in the data set : - ', point)

from scipy_stats import skew

skewness = skew(dataset)
print('Skewness: ', skewness)

from scipy_stats import kurtosis

kurtosis = kurtosis(dataset)
print('Kurtosis: ', kurtosis)

print('Maximum value in the dataset: ', max(dataset))
print('Mininmum value in the dataset: ', min(dataset))
