word_list=['The Shawshank Redemption', 'The Godfather', 'The Godfather: Part II', 'The Dark Knight', 
'12 Angry Men', "Schindler's List", 'The Lord of the Rings: The Return of the King', 'Pulp Fiction',
'The Good, the Bad and the Ugly', 'The Lord of the Rings: The Fellowship of the Ring', 'Fight Club',
'Forrest Gump', 'Inception', 'The Lord of the Rings: The Two Towers', 
'Star Wars: Episode V - The Empire Strikes Back', 'The Matrix', 'Goodfellas',
"One Flew Over the Cuckoo's Nest", 'Seven Samurai', 'Se7en', 'Life Is Beautiful', 'City of God',
 'The Silence of the Lambs', "It's a Wonderful Life", 'Star Wars: Episode IV - A New Hope', 
 'Saving Private Ryan', 'The Green Mile', 'Spirited Away', 'Interstellar', 'Parasite',
 'Léon: The Professional', 'Hara-Kiri', 'The Usual Suspects', 'The Lion King', 'The Pianist', 
 'Back to the Future', 'Terminator 2: Judgment Day', 'American History X', 'Modern Times', 'Gladiator',
'Psycho', 'The Departed', 'City Lights', 'The Intouchables', 'Whiplash', 'Grave of the Fireflies',
'The Prestige', 'Once Upon a Time in the West', 'Casablanca', 'Cinema Paradiso', 'Rear Window', 'Alien', 
'Apocalypse Now', 'Memento', 'The Great Dictator', 'Indiana Jones and the Raiders of the Lost Ark', 
'Django Unchained', 'The Lives of Others', 'Hamilton', 'Paths of Glory', 'Joker', 'WALL-E', 'The Shining',
'Avengers: Infinity War', 'Sunset Boulevard', 'Witness for the Prosecution', 'Oldboy', 
'Spider-Man: Into the Spider-Verse', 'Princess Mononoke', 
'Dr. Strangelove Or: How I Learned To Stop Worrying And Love The Bomb', 'The Dark Knight Rises', 
'Once Upon a Time in America', 'Your Name.', 'Aliens', 'Coco', 'Avengers: Endgame', 'American Beauty', 
'Capernaum', 'Braveheart', 'Das Boot', 'Toy Story', '3 Idiots', 'High and Low', 'Amadeus', 
'Inglourious Basterds', 'Star Wars: Episode VI - Return of the Jedi', 'Good Will Hunting', 
'Taare Zameen Par', 'Reservoir Dogs', '2001: A Space Odyssey', 'Requiem for a Dream', 'Vertigo', 'M', 
'The Hunt', 'Eternal Sunshine of the Spotless Mind', 'Citizen Kane', 'Dangal', "Singin' in the Rain", 
'Bicycle Thieves', 'Full Metal Jacket', 'The Kid', 'Come and See', 'Snatch', 'North by Northwest', 
'A Clockwork Orange', 'Scarface', 'Ikiru', '1917', 'Taxi Driver', 'Incendies', 'A Separation', 
'Lawrence of Arabia', 'Toy Story 3', 'The Sting', 'Amelie', 'Metropolis', 'For a Few Dollars More', 
'The Apartment', 'Double Indemnity', 'To Kill a Mockingbird', 'Up', 'Indiana Jones and The Last Crusade', 
'Heat', 'L.A. Confidential', 'Green Book', 'Die Hard', 'Monty Python and the Holy Grail', 'Batman Begins', 
'Yojimbo', 'Rashomon', 'Downfall', 'Children of Heaven', 'Unforgiven', 'Ran', 'Some Like It Hot', 
"Howl's Moving Castle", 'All About Eve', 'Casino', 'A Beautiful Mind', 'The Wolf of Wall Street', 
'The Great Escape', "Pan's Labyrinth", 'The Secret in Their Eyes', 'There Will Be Blood', 
'Lock, Stock and Two Smoking Barrels', 'Judgment at Nuremberg', 'My Neighbor Totoro', 'Raging Bull', 
'The Treasure of the Sierra Madre', 'Dial M for Murder', 'Three Billboards Outside Ebbing, Missouri',
'Shutter Island', 'The Gold Rush', 'Chinatown', 'My Father and My Son', 'No Country for Old Men', 
'V for Vendetta', 'Inside Out', 'The Elephant Man', 'The Thing', 'The Seventh Seal', 'Warrior', 
'The Sixth Sense', 'Jurassic Park', 'Trainspotting', 'Klaus', 'The Truman Show', 'Gone with the Wind', 
'Finding Nemo', 'Wild Strawberries', 'Stalker', 'Blade Runner', 'Kill Bill: Vol. 1', 'Memories of Murder', 
'The Bridge on the River Kwai', 'Fargo', 'Room',
'Wild Tales', 'Gran Torino', 'The Third Man', 'Tokyo Story', 'On the Waterfront', 'The Deer Hunter', 
'Raatchasan', 'In the Name of the Father', 'Mary and Max', 'The Grand Budapest Hotel', 'Before Sunrise', 
'Gone Girl', 'Catch Me If You Can', 'Hacksaw Ridge', 'Prisoners', 'Persona', 'Andhadhun', 'Anand', 
'Sherlock Jr.', 'The Big Lebowski', 'Autumn Sonata', 'To Be or Not to Be', 'The General', 'Barry Lyndon', 
'How to Train Your Dragon', 'Ford v Ferrari', 'The Bandit', '12 Years a Slave', 
'Mr. Smith Goes to Washington', 'Mad Max: Fury Road', 'Dead Poets Society', 'Million Dollar Baby', 
'Network', 'Stand by Me', 'Harry Potter and the Deathly Hallows: Part 2', 'Ben-Hur', "Hachi: A Dog's Tale", 
'Cool Hand Luke', 'The Handmaiden', 'Soul', 'Platoon', 'Logan', 'Into the Wild', 'Rush', 
'The Wages of Fear', "Monty Python's Life of Brian", 'La Haine', 'The 400 Blows', 
'The Passion of Joan of Arc', 'Spotlight', 'Hotel Rwanda', 'Amores Perros', 'Gangs of Wasseypur', 
'Andrei Rublev', 'Rocky', 'Monsters, Inc.', 'Nausicaä of the Valley of the Wind', 'Time of the Gypsies', 
'Rebecca', 'Before Sunset', 'Rang De Basanti', 'Rififi', 'In the Mood for Love', 'Paris, Texas', 'Drishyam', 
'It Happened One Night', 'Portrait of a Lady on Fire', 'Drishyam', 'The Invisible Guest', 
'A Silent Voice: The Movie', 'The Battle of Algiers', '7. Koğuştaki Mucize', 'Tangerines']